-- liquibase formatted sql

-- changeSet Vladislav:1
create table item_image(
    id int generated by default as identity primary key,
    item_id int references item(id) on delete cascade ,
    url varchar
)
-- rollback drop table item_image;