-- liquibase formatted sql

-- changeSet Vladislav:1
create table person(
    id int generated by default as identity primary key,
    name varchar not null ,
    lastname varchar not null ,
    phone varchar not null ,
    mail varchar not null unique ,
    password varchar,
    city varchar not null ,
    url varchar,
    role varchar not null
)
-- rollback drop table person;